# Generated by Django 5.1.7 on 2025-03-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('minutes_played', models.FloatField()),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
                ('points_per_game', models.FloatField()),
            ],
        ),
    ]
